In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("..\Instructions\JC-201905-citibike-tripdata.csv")
df1.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,311,2019-05-01 00:07:36.4670,2019-05-01 00:12:47.6350,3185,City Hall,40.717733,-74.043845,3279,Dixon Mills,40.721630,-74.049968,29224,Subscriber,1988,1
1,538,2019-05-01 00:08:29.2840,2019-05-01 00:17:27.9410,3681,Grand St,40.715178,-74.037683,3203,Hamilton Park,40.727596,-74.044247,26170,Subscriber,1974,1
2,178,2019-05-01 00:39:36.4750,2019-05-01 00:42:34.9640,3638,Washington St,40.724294,-74.035483,3639,Harborside,40.719252,-74.034234,29517,Subscriber,1988,1
3,317,2019-05-01 01:24:28.0220,2019-05-01 01:29:45.5730,3206,Hilltop,40.731169,-74.057574,3212,Christ Hospital,40.734786,-74.050444,29606,Subscriber,1986,2
4,354,2019-05-01 01:54:39.6660,2019-05-01 02:00:34.1750,3639,Harborside,40.719252,-74.034234,3202,Newport PATH,40.727224,-74.033759,26224,Customer,1986,2

In [3]:
df1.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df1.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,311,2019-05-01 00:07:36.4670,2019-05-01 00:12:47.6350,3185,City Hall,40.717733,-74.043845,3279,Dixon Mills,40.721630,-74.049968,29224,Subscriber,1988,1
1,538,2019-05-01 00:08:29.2840,2019-05-01 00:17:27.9410,3681,Grand St,40.715178,-74.037683,3203,Hamilton Park,40.727596,-74.044247,26170,Subscriber,1974,1
2,178,2019-05-01 00:39:36.4750,2019-05-01 00:42:34.9640,3638,Washington St,40.724294,-74.035483,3639,Harborside,40.719252,-74.034234,29517,Subscriber,1988,1
3,317,2019-05-01 01:24:28.0220,2019-05-01 01:29:45.5730,3206,Hilltop,40.731169,-74.057574,3212,Christ Hospital,40.734786,-74.050444,29606,Subscriber,1986,2
4,354,2019-05-01 01:54:39.6660,2019-05-01 02:00:34.1750,3639,Harborside,40.719252,-74.034234,3202,Newport PATH,40.727224,-74.033759,26224,Customer,1986,2

In [4]:
df2 = pd.read_csv("..\Instructions\JC-201906-citibike-tripdata.csv")
df2.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,316,2019-06-01 00:05:55.7210,2019-06-01 00:11:11.9940,3187,Warren St,40.721124,-74.038051,3199,Newport Pkwy,40.728745,-74.032108,29677,Subscriber,1993,1
1,280,2019-06-01 00:08:09.0920,2019-06-01 00:12:50.0730,3185,City Hall,40.717733,-74.043845,3267,Morris Canal,40.712419,-74.038526,29571,Subscriber,1984,1
2,2162,2019-06-01 00:13:11.8800,2019-06-01 00:49:14.3640,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,26208,Customer,1969,0
3,2184,2019-06-01 00:13:30.1110,2019-06-01 00:49:54.2250,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,29487,Customer,1969,0
4,139,2019-06-01 00:13:31.8520,2019-06-01 00:15:51.7880,3207,Oakland Ave,40.737604,-74.052478,3207,Oakland Ave,40.737604,-74.052478,29592,Subscriber,1994,1

In [5]:
df2.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df2.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,316,2019-06-01 00:05:55.7210,2019-06-01 00:11:11.9940,3187,Warren St,40.721124,-74.038051,3199,Newport Pkwy,40.728745,-74.032108,29677,Subscriber,1993,1
1,280,2019-06-01 00:08:09.0920,2019-06-01 00:12:50.0730,3185,City Hall,40.717733,-74.043845,3267,Morris Canal,40.712419,-74.038526,29571,Subscriber,1984,1
2,2162,2019-06-01 00:13:11.8800,2019-06-01 00:49:14.3640,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,26208,Customer,1969,0
3,2184,2019-06-01 00:13:30.1110,2019-06-01 00:49:54.2250,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,29487,Customer,1969,0
4,139,2019-06-01 00:13:31.8520,2019-06-01 00:15:51.7880,3207,Oakland Ave,40.737604,-74.052478,3207,Oakland Ave,40.737604,-74.052478,29592,Subscriber,1994,1

In [6]:
df3 = pd.read_csv("..\Instructions\JC-201907-citibike-tripdata.csv")
df3.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1793,2019-07-01 00:00:36.6150,2019-07-01 00:30:30.5940,3186,Grove St PATH,40.719586,-74.043117,3198,Heights Elevator,40.748716,-74.040443,29595,Subscriber,1978,1
1,434,2019-07-01 00:02:54.6150,2019-07-01 00:10:09.0370,3206,Hilltop,40.731169,-74.057574,3280,Astor Place,40.719282,-74.071262,29647,Subscriber,1988,1
2,251,2019-07-01 00:03:27.5670,2019-07-01 00:07:38.6080,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,26271,Subscriber,1986,1
3,636,2019-07-01 00:03:56.1690,2019-07-01 00:14:32.4180,3206,Hilltop,40.731169,-74.057574,3281,Leonard Gordon Park,40.745910,-74.057271,26225,Customer,1996,2
4,623,2019-07-01 00:04:16.2060,2019-07-01 00:14:40.0500,3206,Hilltop,40.731169,-74.057574,3281,Leonard Gordon Park,40.745910,-74.057271,29230,Customer,1989,1

In [7]:
df3.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df3.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1793,2019-07-01 00:00:36.6150,2019-07-01 00:30:30.5940,3186,Grove St PATH,40.719586,-74.043117,3198,Heights Elevator,40.748716,-74.040443,29595,Subscriber,1978,1
1,434,2019-07-01 00:02:54.6150,2019-07-01 00:10:09.0370,3206,Hilltop,40.731169,-74.057574,3280,Astor Place,40.719282,-74.071262,29647,Subscriber,1988,1
2,251,2019-07-01 00:03:27.5670,2019-07-01 00:07:38.6080,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,26271,Subscriber,1986,1
3,636,2019-07-01 00:03:56.1690,2019-07-01 00:14:32.4180,3206,Hilltop,40.731169,-74.057574,3281,Leonard Gordon Park,40.745910,-74.057271,26225,Customer,1996,2
4,623,2019-07-01 00:04:16.2060,2019-07-01 00:14:40.0500,3206,Hilltop,40.731169,-74.057574,3281,Leonard Gordon Park,40.745910,-74.057271,29230,Customer,1989,1

In [8]:
df4 = pd.read_csv("..\Instructions\JC-201908-citibike-tripdata.csv")
df4.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,261,2019-08-01 00:14:55.9900,2019-08-01 00:19:17.4780,3205,JC Medical Center,40.716540,-74.049638,3192,Liberty Light Rail,40.711242,-74.055701,26268,Subscriber,1980,1
1,172,2019-08-01 00:23:06.9910,2019-08-01 00:25:59.1480,3279,Dixon Mills,40.721630,-74.049968,3186,Grove St PATH,40.719586,-74.043117,26162,Subscriber,1996,1
2,525,2019-08-01 00:23:28.6170,2019-08-01 00:32:13.7000,3199,Newport Pkwy,40.728745,-74.032108,3203,Hamilton Park,40.727596,-74.044247,29279,Subscriber,1991,1
3,219,2019-08-01 00:32:36.1410,2019-08-01 00:36:15.2730,3187,Warren St,40.721124,-74.038051,3185,City Hall,40.717733,-74.043845,29598,Subscriber,1988,1
4,262,2019-08-01 00:41:26.6700,2019-08-01 00:45:49.3530,3186,Grove St PATH,40.719586,-74.043117,3272,Jersey & 3rd,40.723332,-74.045953,26162,Subscriber,1960,1

In [9]:
df4.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df4.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,261,2019-08-01 00:14:55.9900,2019-08-01 00:19:17.4780,3205,JC Medical Center,40.716540,-74.049638,3192,Liberty Light Rail,40.711242,-74.055701,26268,Subscriber,1980,1
1,172,2019-08-01 00:23:06.9910,2019-08-01 00:25:59.1480,3279,Dixon Mills,40.721630,-74.049968,3186,Grove St PATH,40.719586,-74.043117,26162,Subscriber,1996,1
2,525,2019-08-01 00:23:28.6170,2019-08-01 00:32:13.7000,3199,Newport Pkwy,40.728745,-74.032108,3203,Hamilton Park,40.727596,-74.044247,29279,Subscriber,1991,1
3,219,2019-08-01 00:32:36.1410,2019-08-01 00:36:15.2730,3187,Warren St,40.721124,-74.038051,3185,City Hall,40.717733,-74.043845,29598,Subscriber,1988,1
4,262,2019-08-01 00:41:26.6700,2019-08-01 00:45:49.3530,3186,Grove St PATH,40.719586,-74.043117,3272,Jersey & 3rd,40.723332,-74.045953,26162,Subscriber,1960,1

In [10]:
df5 = pd.read_csv("..\Instructions\JC-201909-citibike-tripdata.csv")
df5.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,145,2019-09-01 00:00:37.6920,2019-09-01 00:03:03.0100,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,29303,Subscriber,1991,1
1,212,2019-09-01 00:03:00.6000,2019-09-01 00:06:33.3420,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,29297,Subscriber,1993,2
2,569,2019-09-01 00:07:13.0020,2019-09-01 00:16:42.8610,3214,Essex Light Rail,40.712774,-74.036486,3184,Paulus Hook,40.714145,-74.033552,29435,Customer,1977,1
3,1380,2019-09-01 00:07:25.3350,2019-09-01 00:30:26.1640,3214,Essex Light Rail,40.712774,-74.036486,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,29509,Subscriber,1965,1
4,1346,2019-09-01 00:07:56.4670,2019-09-01 00:30:22.5440,3214,Essex Light Rail,40.712774,-74.036486,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,29226,Subscriber,1968,2

In [11]:
df5.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df5.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,145,2019-09-01 00:00:37.6920,2019-09-01 00:03:03.0100,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,29303,Subscriber,1991,1
1,212,2019-09-01 00:03:00.6000,2019-09-01 00:06:33.3420,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,29297,Subscriber,1993,2
2,569,2019-09-01 00:07:13.0020,2019-09-01 00:16:42.8610,3214,Essex Light Rail,40.712774,-74.036486,3184,Paulus Hook,40.714145,-74.033552,29435,Customer,1977,1
3,1380,2019-09-01 00:07:25.3350,2019-09-01 00:30:26.1640,3214,Essex Light Rail,40.712774,-74.036486,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,29509,Subscriber,1965,1
4,1346,2019-09-01 00:07:56.4670,2019-09-01 00:30:22.5440,3214,Essex Light Rail,40.712774,-74.036486,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,29226,Subscriber,1968,2

In [12]:
df6 = pd.read_csv("..\Instructions\JC-201910-citibike-tripdata.csv")
df6.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,892,2019-10-01 00:20:05.0140,2019-10-01 00:34:57.3800,3275,Columbus Drive,40.718355,-74.038914,3280,Astor Place,40.719282,-74.071262,29544,Subscriber,1976,1
1,374,2019-10-01 00:43:48.8790,2019-10-01 00:50:03.8190,3211,Newark Ave,40.721525,-74.046305,3791,Hoboken Ave at Monmouth St,40.735208,-74.046964,29536,Subscriber,1984,1
2,170,2019-10-01 01:35:51.8630,2019-10-01 01:38:42.5470,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,26304,Subscriber,1986,1
3,946,2019-10-01 02:55:53.4000,2019-10-01 03:11:40.2710,3272,Jersey & 3rd,40.723332,-74.045953,3679,Bergen Ave,40.722104,-74.071455,29496,Customer,1969,0
4,517,2019-10-01 03:10:16.1290,2019-10-01 03:18:53.6350,3206,Hilltop,40.731169,-74.057574,3210,Pershing Field,40.742677,-74.051789,26205,Subscriber,1969,1

In [13]:
df6.rename(columns = {'Trip Duration': 'tripduration', 'Start Time': 'starttime', 
                      'Stop Time': 'stoptime', 'Gender':'gender', "User Type": "usertype",
                      'Bike ID': 'bikeid', 'Birth Year': 'birth year', 'Start Station ID': 'start station id',
                      'Start Station Name': 'start station name', 'Start Station Latitude': 'start station latitude',
                      'Start Station Longitude': 'start station longitude', 'End Station ID': 'end station id', 
                      'End Station Name': 'end station name', 'End Station Latitude': 'end station latitude',
                      'End Station Longitude': 'end station longitude'}, inplace = True)
df6.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,892,2019-10-01 00:20:05.0140,2019-10-01 00:34:57.3800,3275,Columbus Drive,40.718355,-74.038914,3280,Astor Place,40.719282,-74.071262,29544,Subscriber,1976,1
1,374,2019-10-01 00:43:48.8790,2019-10-01 00:50:03.8190,3211,Newark Ave,40.721525,-74.046305,3791,Hoboken Ave at Monmouth St,40.735208,-74.046964,29536,Subscriber,1984,1
2,170,2019-10-01 01:35:51.8630,2019-10-01 01:38:42.5470,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,26304,Subscriber,1986,1
3,946,2019-10-01 02:55:53.4000,2019-10-01 03:11:40.2710,3272,Jersey & 3rd,40.723332,-74.045953,3679,Bergen Ave,40.722104,-74.071455,29496,Customer,1969,0
4,517,2019-10-01 03:10:16.1290,2019-10-01 03:18:53.6350,3206,Hilltop,40.731169,-74.057574,3210,Pershing Field,40.742677,-74.051789,26205,Subscriber,1969,1

In [14]:
citibike_2019 = pd.concat([df1, df2, df3, df4, df5, df6])
citibike_2019

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,311,2019-05-01 00:07:36.4670,2019-05-01 00:12:47.6350,3185,City Hall,40.717733,-74.043845,3279,Dixon Mills,40.721630,-74.049968,29224,Subscriber,1988,1
1,538,2019-05-01 00:08:29.2840,2019-05-01 00:17:27.9410,3681,Grand St,40.715178,-74.037683,3203,Hamilton Park,40.727596,-74.044247,26170,Subscriber,1974,1
2,178,2019-05-01 00:39:36.4750,2019-05-01 00:42:34.9640,3638,Washington St,40.724294,-74.035483,3639,Harborside,40.719252,-74.034234,29517,Subscriber,1988,1
3,317,2019-05-01 01:24:28.0220,2019-05-01 01:29:45.5730,3206,Hilltop,40.731169,-74.057574,3212,Christ Hospital,40.734786,-74.050444,29606,Subscriber,1986,2
4,354,2019-05-01 01:54:39.6660,2019-05-01 02:00:34.1750,3639,Harborside,40.719252,-74.034234,3202,Newport PATH,40.727224,-74.033759,26224,Customer,1986,2
5,357,2019-05-01 01:54:43.6300,2019-05-01 02:00:41.0210,3639,Harborside,40.719252,-74.034234,3202,Newport PATH,40.727224,-74.033759,29541,Customer,1986,1
6,138,2019-05-01 02:25:04.8320,2019-05-01 02:27:23.0580,3183,Exchange Place,40.716247,-74.033459,3681,Grand St,40.715178,-74.037683,29280,Subscriber,1979,1
7,299,2019-05-01 03:50:09.1180,2019-05-01 03:55:08.8850,3194,McGinley Square,40.725340,-74.067622,3679,Bergen Ave,40.722104,-74.071455,29479,Subscriber,1987,1
8,296,2019-05-01 04:44:27.7800,2019-05-01 04:49:24.4570,3203,Hamilton Park,40.727596,-74.044247,3202,Newport PATH,40.727224,-74.033759,29554,Subscriber,1967,1
9,811,2019-05-01 04:55:48.9470,2019-05-01 05:09:20.2810,3207,Oakland Ave,40.737604,-74.052478,3185,City Hall,40.717733,-74.043845,29666,Subscriber,1984,2
10,293,2019-05-01 05:06:54.6420,2019-05-01 05:11:48.0680,3272,Jersey & 3rd,40.723332,-74.045953,3638,Washington St,40.724294,-74.035483,29674,Subscriber,1964,1
11,287,2019-05-01 05:15:41.5460,2019-05-01 05:20:29.0360,3203,Hamilton Park,40.727596,-74.044247,3186,Grove St PATH,40.719586,-74.043117,29449,Subscriber,1973,2
12,268,2019-05-01 05:22:29.3550,2019-05-01 05:26:57.7180,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,29449,Subscriber,1990,1
13,234,2019-05-01 05:23:58.9310,2019-05-01 05:27:53.2280,3278,Monmouth and 6th,40.725685,-74.048790,3186,Grove St PATH,40.719586,-74.043117,29614,Subscriber,1985,1
14,156,2019-05-01 05:27:32.1140,2019-05-01 05:30:08.4270,3279,Dixon Mills,40.721630,-74.049968,3186,Grove St PATH,40.719586,-74.043117,26162,Subscriber,1976,1
15,191,2019-05-01 05:37:13.8920,2019-05-01 05:40:25.6140,3276,Marin Light Rail,40.714584,-74.042817,3186,Grove St PATH,40.719586,-74.043117,29577,Subscriber,1979,2
16,166,2019-05-01 05:41:10.7490,2019-05-01 05:43:57.6730,3267,Morris Canal,40.712419,-74.038526,3183,Exchange Place,40.716247,-74.033459,29550,Subscriber,1994,2
17,292,2019-05-01 05:42:31.6720,2019-05-01 05:47:24.1310,3677,Glenwood Ave,40.727551,-74.071061,3195,Sip Ave,40.730897,-74.063913,29668,Subscriber,1974,1
18,390,2019-05-01 05:45:03.7860,2019-05-01 05:51:34.5880,3209,Brunswick St,40.724176,-74.050656,3639,Harborside,40.719252,-74.034234,29297,Subscriber,1987,2
19,235,2019-05-01 05:51:16.2570,2019-05-01 05:55:11.4400,3203,Hamilton Park,40.727596,-74.044247,3186,Grove St PATH,40.719586,-74.043117,26200,Subscriber,1987,1
20,253,2019-05-01 05:53:33.2840,2019-05-01 05:57:46.5540,3214,Essex Light Rail,40.712774,-74.036486,3275,Columbus Drive,40.718355,-74.038914,29299,Subscriber,1983,2
21,358,2019-05-01 05:54:08.4790,2019-05-01 06:00:07.0700,3225,Baldwin at Montgomery,40.723659,-74.064194,3195,Sip Ave,40.730897,-74.063913,29612,Subscriber,1962,1
22,305,2019-05-01 05:57:32.5340,2019-05-01 06:02:38.1330,3203,Hamilton Park,40.727596,-74.044247,3639,Harborside,40.719252,-74.034234,29534,Subscriber,1964,1
23,220,2019-05-01 06:01:06.2950,2019-05-01 06:04:46.3050,3269,Brunswick & 6th,40.726012,-74.050389,3186,Grove St PATH,40.719586,-74.043117,26307,Subscriber,1989,2
24,287,2019-05-01 06:01:18.8850,2019-05-01 06:06:06.3640,3678,Fairmount Ave,40.725726,-74.071959,3195,Sip Ave,40.730897,-74.063913,26214,Subscriber,1967,1
25,188,2019-05-01 06:02:41.7050,2019-05-01 06:05:49.7330,3270,Jersey & 6th St,40.725289,-74.045572,3186,Grove St PATH,40.719586,-74.043117,29653,Subscriber,1976,1
26,124,2019-05-01 06:06:07.6050,2019-05-01 06:08:11.9590,3279,Dixon Mills,40.721630,-74.049968,3186,Grove St PATH,40.719586,-74.043117,28771,Subscriber,1982,1
27,193,2019-05-01 06:07:23.8650,2019-05-01 06:10:37.1990,3199,Newport Pkwy,40.728745,-74.032108,3638,Washington St,40.724294,-74.035483,29662,Subscriber,1992,1
28,83,2019-05-01 06:07:58.3730,2019-05-01 06:09:21.5580,3639,Harborside,40.719252,-74.034234,3183,Exchange Place,40.716247,-74.033459,29534,Subscriber,1988,1
29,248,2019-05-01 06:08:16.3530,2019-05-01 06:12:25.0170,3270,Jersey & 6th St,40.725289,-74.045572,3186,Grove St PATH,40.719586,-74.043117,29245,Subscriber,1981,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42223,443,2019-10-31 22:52:05.2090,2019-10-31 22:59:28.2990,3195,Sip Ave,40.730897,-74.063913,3677,Glenwood Ave,40.727551,-74.071061,26225,Subscriber,1993,1
42224,103,2019-10-31 22:55:39.3770,2019-10-31 22:57:22.5910,3213,Van Vorst Park,40.718489,-74.047727,3213,Van Vorst Park,40.718489,-74.047727,29284,Subscriber,1986,1
42225,199,2019-10-31 22:57:00.1020,2019-10-31 23:00:19.9520,3186,Grove St PATH,40.719586,-74.043117,3272,Jersey & 3rd,40.723332,-74.045953,29662,Subscriber,1957,2
42226,198,2019-10-31 22:57:43.3570,2019-10-31 23:01:01.7460,3186,Grove St PATH,40.719586,-74.043117,3279,Dixon Mills,40.721630,-74.049968,29640,Subscriber,1984,1
42227,262,2019-10-31 22:57:54.0410,2019-10-31 23:02:16.6680,3186,Grove St PATH,40.719586,-74.043117,3203,Hamilton Park,40.727596,-74.044247,29278,Subscriber,1990,2
42228,218,2019-10-31 22:58:14.3980,2019-10-31 23:01:53.1010,3270,Jersey & 6th St,40.725289,-74.045572,3273,Manila & 1st,40.721651,-74.042884,29235,Subscriber,1976,1
42229,1060,2019-10-31 22:58:36.4560,2019-10-31 23:16:16.5510,3186,Grove St PATH,40.719586,-74.043117,3268,Lafayette Park,40.713464,-74.062859,29521,Subscriber,1978,1
42230,1072,2019-10-31 23:01:00.9580,2019-10-31 23:18:53.4950,3187,Warren St,40.721124,-74.038051,3185,City Hall,40.717733,-74.043845,26288,Subscriber,1985,1
42231,949,2019-10-31 23:02:27.5920,2019-10-31 23:18:17.1980,3198,Heights Elevator,40.748716,-74.040443,3195,Sip Ave,40.730897,-74.063913,29576,Subscriber,1958,1
42232,2937,2019-10-31 23:03:52.3200,2019-10-31 23:52:49.4380,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,29655,Customer,1992,1
42233,244,2019-10-31 23:04:05.5160,2019-10-31 23:08:10.2630,3199,Newport Pkwy,40.728745,-74.032108,3638,Washington St,40.724294,-74.035483,29660,Customer,1990,1
42234,803,2019-10-31 23:04:42.3960,2019-10-31 23:18:06.0330,3194,McGinley Square,40.725340,-74.067622,3210,Pershing Field,40.742677,-74.051789,29643,Customer,1996,1
42235,559,2019-10-31 23:11:39.4100,2019-10-31 23:20:58.4860,3199,Newport Pkwy,40.728745,-74.032108,3791,Hoboken Ave at Monmouth St,40.735208,-74.046964,29214,Subscriber,1995,2
42236,582,2019-10-31 23:14:55.0210,2019-10-31 23:24:37.9540,3214,Essex Light Rail,40.712774,-74.036486,3186,Grove St PATH,40.719586,-74.043117,29645,Subscriber,1976,1
42237,557,2019-10-31 23:17:04.6650,2019-10-31 23:26:21.7910,3194,McGinley Square,40.725340,-74.067622,3211,Newark Ave,40.721525,-74.046305,29231,Customer,1969,0
42238,145,2019-10-31 23:22:15.2520,2019-10-31 23:24:41.1790,3186,Grove St PATH,40.719586,-74.043117,3279,Dixon Mills,40.721630,-74.049968,29544,Subscriber,1975,1
42239,399,2019-10-31 23:24:43.9130,2019-10-31 23:31:23.6240,3199,Newport Pkwy,40.728745,-74.032108,3203,Hamilton Park,40.727596,-74.044247,26314,Subscriber,1964,1
42240,833,2019-10-31 23:25:58.6490,2019-10-31 23:39:51.9050,3277,Communipaw & Berry Lane,40.714358,-74.066611,3277,Communipaw & Berry Lane,40.714358,-74.066611,26173,Subscriber,2001,2
42241,544,2019-10-31 23:26:03.8890,2019-10-31 23:35:08.2060,3194,McGinley Square,40.725340,-74.067622,3191,Union St,40.718211,-74.083639,29207,Subscriber,1962,1
42242,436,2019-10-31 23:28:02.8770,2019-10-31 23:35:19.0850,3225,Baldwin at Montgomery,40.723659,-74.064194,3193,Lincoln Park,40.724605,-74.078406,29434,Customer,1995,1
42243,304,2019-10-31 23:30:54.0540,2019-10-31 23:35:58.7460,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,26166,Subscriber,1997,1
42244,441,2019-10-31 23:32:06.5770,2019-10-31 23:39:27.9200,3211,Newark Ave,40.721525,-74.046305,3681,Grand St,40.715178,-74.037683,29233,Subscriber,1978,1
42245,118,2019-10-31 23:36:38.0390,2019-10-31 23:38:36.9800,3195,Sip Ave,40.730897,-74.063913,3640,Journal Square,40.733670,-74.062500,29576,Subscriber,1987,1
42246,552,2019-10-31 23:37:37.2430,2019-10-31 23:46:50.1360,3207,Oakland Ave,40.737604,-74.052478,3211,Newark Ave,40.721525,-74.046305,26305,Customer,1990,1
42247,129,2019-10-31 23:38:46.4110,2019-10-31 23:40:55.9510,3640,Journal Square,40.733670,-74.062500,3220,5 Corners Library,40.734961,-74.059503,29576,Subscriber,1987,1
42248,287,2019-10-31 23:42:25.1120,2019-10-31 23:47:12.6180,3209,Brunswick St,40.724176,-74.050656,3186,Grove St PATH,40.719586,-74.043117,26160,Subscriber,1987,1
42249,532,2019-10-31 23:48:07.5720,2019-10-31 23:56:59.7280,3187,Warren St,40.721124,-74.038051,3187,Warren St,40.721124,-74.038051,26292,Subscriber,1976,0
42250,202,2019-10-31 23:50:04.3480,2019-10-31 23:53:26.6230,3681,Grand St,40.715178,-74.037683,3185,City Hall,40.717733,-74.043845,26180,Subscriber,1977,1
42251,841,2019-10-31 23:53:24.5280,2019-11-01 00:07:25.8950,3199,Newport Pkwy,40.728745,-74.032108,3483,Montgomery St,40.719420,-74.050990,29655,Subscriber,1958,1
42252,268,2019-10-31 23:53:45.6170,2019-10-31 23:58:13.8980,3203,Hamilton Park,40.727596,-74.044247,3186,Grove St PATH,40.719586,-74.043117,26314,Subscriber,1964,1